### PR TITLE
Clean up syntax

### PR DESCRIPTION
**Pull request by aemkei**
Cleanup and lint syntax, move vars to top of method, add link to Github repository and lay out conditions.

### CODE REVIEW

**Comment by Xethron** [comment]
Why hasn't this been merged in?

**Comment by tparkin** [comment]
@aemkei Thanks for these improvements.

@Xethron It wasn't previously merged in because I wrote this as I needed it, and never looked back. I appreciate your comment to bring this pending pull request to my attention. It's now merged!

**Comment by Xethron** [comment]
Sweet, just started using your tool, thanks for the work, made my life a lot easier!

**Comment by tparkin** [comment]
@Xethron Glad to hear! :)

**Pull request merged**
